//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MbisSystem.Model.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Isler
    {
        public int IsID { get; set; }

        [DisplayName("Firma Adý")]
        public string Baslik { get; set; }

        public string Aciklama { get; set; }
        public int Olusturan { get; set; }
        public int Durum { get; set; }
        public Nullable<int> Atanan { get; set; }
        public Nullable<int> Atanan2 { get; set; }
        public string AtananIsim { get; set; }
        public string OlusturanIsim { get; set; }
    }
}
