//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MbisSystem.Model.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Personel
    {
        public int PersonelID { get; set; }
        public string PersonelAd { get; set; }
        public int Durum { get; set; }
        [DisplayName("Toplam Ýþ Sayýsý")]
        public int IsSayisi { get; set; }

        [DisplayName("Kullanýcý Adý")]
        [Required(ErrorMessage ="Bu alan doldurulmak zorundadýr.")]
        public string username { get; set; }
        [DisplayName("Þifre")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Bu alan doldurulmak zorundadýr.")]
        public string password { get; set; }
        public string LogErrorMessage { get; set; }
        public string mail { get; set; }
    }
}
